connecture:

  outputs:

    athena:
      type: athena
      region_name: "{{ env_var('AWS_REGION') }}"
      s3_staging_dir: "s3://{{ env_var('ENV_PREFIX') }}-{{ env_var('BASE_PREFIX') }}-lakehouse-bucket/athena_results/"
      s3_data_dir: "s3://{{ env_var('ENV_PREFIX') }}-{{ env_var('BASE_PREFIX') }}-lakehouse-bucket/medallion/"
      database: "{{ env_var('LANDING_DATABASE') }}"
      schema: ""
      num_retries: 1
      threads: 4
      debug_query_state: true # we sure?

  target: "{{ env_var('DBT_TARGET') }}"
